import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by create next app + sanity',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-black'>
      <div className=' mt-13 ml-10  '>
      <header className=' mt-3 ml-15  gap-2 flex align-center justify-between min-w-fit  '>
    <Link href="/" className=' font-extrabold text-2xl bg-gradient-to-br from-blue-500 via-pink-300 to-red-500 bg-clip-text text-transparent'>LoGo</Link>  
    <div className='gap-3  '>
    <Link href="/" className='mr-10  font-extrabold text-2xl bg-gradient-to-br from-blue-500 via-pink-300 to-red-500 bg-clip-text text-transparent'>Home</Link>  
    <Link href="/" className='mr-10  font-extrabold text-2xl bg-gradient-to-br from-blue-500 via-pink-300 to-red-500 bg-clip-text text-transparent'>Blog</Link> 
    <Link href="/" className='mr-10  font-extrabold text-2xl bg-gradient-to-br from-blue-500 via-pink-300 to-red-500 bg-clip-text text-transparent'>Contact</Link> 
    <Link href="/" className='mr-10  font-extrabold text-2xl bg-gradient-to-br from-blue-500 via-pink-300 to-red-500 bg-clip-text text-transparent'>About</Link> 
    </div> 
  
       
      </header>
      <main className=''>{children}</main>
      </div>
    </html>
  )
}
